#!/usr/bin/env bash
# Module: messaging/imessage
# Sets up iMessage integration for your Claude Code assistant.
# Requires macOS with Messages.app.

set -euo pipefail

ENV_FILE="${DEPLOY_BASE:-$HOME}/.env"
AGENT_NAME="${AGENT_NAME:-assistant}"

print_step() { echo ""; echo "  --> $1"; }
print_ok()   { echo "  [OK] $1"; }
print_warn() { echo "  [!]  $1"; }

echo ""
echo "========================================"
echo "  iMessage Integration Setup"
echo "  Agent: $AGENT_NAME"
echo "========================================"

# ── Step 1: macOS check ────────────────────────────────────────────────────
if [[ "$(uname -s)" != "Darwin" ]]; then
  echo ""
  echo "  ERROR: iMessage integration requires macOS."
  echo ""
  echo "  This module relies on the Messages.app plugin, which only runs on macOS."
  echo "  The Claude Code iMessage plugin connects to the system Messages database"
  echo "  and the Messages.app process — neither of which is available on Linux or Windows."
  echo ""
  echo "  If you are deploying your assistant on a Linux server (VPS, etc.), consider:"
  echo ""
  echo "    - Telegram module   (modules/messaging/telegram/install.sh)"
  echo "    - Discord module    (modules/messaging/discord/install.sh)"
  echo ""
  echo "  Both work cross-platform and require no local GUI apps."
  echo ""
  exit 1
fi

print_ok "macOS detected: $(sw_vers -productVersion)"

# ── Step 2: Check Messages.app ────────────────────────────────────────────
print_step "Checking Messages.app"
if [ -d "/Applications/Messages.app" ]; then
  print_ok "Messages.app is installed"
else
  echo ""
  print_warn "Messages.app not found at /Applications/Messages.app"
  echo "  iMessage integration requires Messages.app to be installed and signed into"
  echo "  your Apple ID. Messages.app is included with macOS."
  echo ""
  echo "  If it is installed in a non-standard location, you may proceed, but"
  echo "  the plugin may not function correctly."
  echo ""
fi

# ── Step 3: Apple ID sign-in reminder ─────────────────────────────────────
print_step "Ensure Messages.app is signed in"
echo ""
echo "  iMessage access requires Messages.app to be:"
echo "  1. Open and running"
echo "  2. Signed in to your Apple ID"
echo "  3. Granted any required accessibility permissions (see below)"
echo ""
echo "  To check: open Messages.app > Messages menu > Preferences > iMessage tab"
echo "  Your Apple ID should be listed and show as active."
echo ""

# ── Step 4: Accessibility and Full Disk Access ─────────────────────────────
print_step "Required macOS permissions"
echo ""
echo "  The iMessage plugin may require the following macOS permissions:"
echo ""
echo "  Full Disk Access (for reading the Messages database):"
echo "    System Settings > Privacy & Security > Full Disk Access"
echo "    Enable access for: Terminal (or your terminal app) and/or claude"
echo ""
echo "  Automation (for controlling Messages.app):"
echo "    System Settings > Privacy & Security > Automation"
echo "    Allow your terminal or claude to control 'Messages'"
echo ""
echo "  If Claude Code requests these permissions during launch, approve them."
echo ""

# ── Step 5: How to start Claude Code with iMessage ────────────────────────
print_step "Starting your assistant with iMessage"
echo ""
echo "  Start Claude Code with the iMessage plugin:"
echo ""
echo "    claude --channels plugin:imessage@claude-plugins-official \\"
echo "           --system-prompt \"\$(cat \$SOUL_FILE)\" \\"
echo "           --dangerously-skip-permissions"
echo ""
echo "  This must run on your Mac, not on a remote server."
echo ""
echo "  If you are using the launch script generated by setup.sh:"
echo ""
echo "    ${DEPLOY_BASE:-$HOME}/.${AGENT_NAME}/launch.sh"
echo ""

# ── Step 6: Privacy note ───────────────────────────────────────────────────
print_step "Privacy note"
echo ""
echo "  The iMessage plugin gives your assistant access to your Messages history"
echo "  and the ability to send messages as you."
echo ""
echo "  What this means:"
echo "  - Your assistant can read incoming iMessages sent to you"
echo "  - Your assistant can send replies from your Apple ID"
echo "  - Messages are processed locally — they are passed to Claude's API for"
echo "    response generation, but not stored beyond the session"
echo ""
echo "  Be thoughtful about which conversations your assistant can access."
echo "  If you have sensitive threads, consider whether iMessage is the right"
echo "  channel for this integration."
echo ""

echo "========================================"
echo "  iMessage module setup complete."
echo "========================================"
echo ""
