#!/usr/bin/env bash
# modules/agents/job-search/install.sh
# Sets up the job search sub-agent for personal-ai-playbook.
#
# Usage: DEPLOY_BASE=~/.max AGENT_NAME=max bash install.sh
# Required env vars:
#   DEPLOY_BASE  — root deploy directory (e.g. ~/.max)
#   AGENT_NAME   — the persona name (e.g. max)

set -euo pipefail

# ── Defaults ─────────────────────────────────────────────────────────────────
DEPLOY_BASE="${DEPLOY_BASE:-$HOME/.max}"
AGENT_NAME="${AGENT_NAME:-max}"
ENV_FILE="${DEPLOY_BASE}/.env"
AGENTS_CONFIG_DIR="${DEPLOY_BASE}/${AGENT_NAME}-config"
AGENTS_JSON="${AGENTS_CONFIG_DIR}/agents.json"
CONFIG_DIR="${DEPLOY_BASE}/.${AGENT_NAME}/config"
PREFS_FILE="${CONFIG_DIR}/job-search.yaml"

# ── Helpers ───────────────────────────────────────────────────────────────────
log()  { echo "[job-search] $*"; }
ok()   { echo "  [ok] $*"; }
ask()  { local var="$1" prompt="$2" default="${3:-}"
         if [[ -n "$default" ]]; then
           read -r -p "  ${prompt} [${default}]: " input
           eval "${var}=\"${input:-$default}\""
         else
           read -r -p "  ${prompt}: " input
           eval "${var}=\"${input}\""
         fi
}

require_env() {
  if [[ -z "${DEPLOY_BASE:-}" || -z "${AGENT_NAME:-}" ]]; then
    echo "ERROR: DEPLOY_BASE and AGENT_NAME must be set."
    echo "  Example: DEPLOY_BASE=~/.max AGENT_NAME=max bash install.sh"
    exit 1
  fi
}

env_set() {
  local key="$1" val="$2"
  if grep -q "^export ${key}=" "$ENV_FILE" 2>/dev/null; then
    sed -i "s|^export ${key}=.*|export ${key}=${val}|" "$ENV_FILE"
    ok "Updated ${key} in .env"
  else
    echo "export ${key}=${val}" >> "$ENV_FILE"
    ok "Added ${key} to .env"
  fi
}

# ── Main ──────────────────────────────────────────────────────────────────────
require_env

log "Installing job-search sub-agent"
log "  DEPLOY_BASE : ${DEPLOY_BASE}"
log "  AGENT_NAME  : ${AGENT_NAME}"
echo ""

# 1. Collect job search preferences
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Job Search Preferences Setup"
echo "  (Press Enter to accept defaults or skip optional fields)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

ask TARGET_ROLES       "Target job titles (comma-separated)"             "Software Engineer, Senior Engineer"
ask TARGET_INDUSTRIES  "Target industries (comma-separated)"             "Technology, SaaS, Fintech"
ask LOCATION_PREF      "Location preference"                             "Remote"
ask WILLING_TO_RELOCATE "Willing to relocate? (yes/no)"                 "no"
ask SALARY_MIN         "Minimum acceptable salary (USD, leave blank to skip)" ""
ask EXPERIENCE_YEARS   "Years of relevant experience"                   ""
ask RESUME_PATH        "Path to your resume file (leave blank to skip)" ""
ask EXCLUDE_COMPANIES  "Companies to exclude (comma-separated, or leave blank)" ""
ask NOTES              "Any other preferences or constraints"            ""

echo ""
log "Saving preferences to ${PREFS_FILE}..."
mkdir -p "$CONFIG_DIR"

cat > "$PREFS_FILE" << YAML
# Job Search Preferences
# Generated by job-search/install.sh on $(date +%Y-%m-%d)
# Edit this file directly to update your preferences.

target_roles:
$(echo "$TARGET_ROLES" | tr ',' '\n' | sed 's/^ *\(.*\) *$/  - "\1"/')

target_industries:
$(echo "$TARGET_INDUSTRIES" | tr ',' '\n' | sed 's/^ *\(.*\) *$/  - "\1"/')

location:
  preference: "${LOCATION_PREF}"
  willing_to_relocate: ${WILLING_TO_RELOCATE}

salary:
  minimum_usd: "${SALARY_MIN}"

experience_years: "${EXPERIENCE_YEARS}"

resume_path: "${RESUME_PATH}"

exclude_companies:
$(if [[ -n "$EXCLUDE_COMPANIES" ]]; then
  echo "$EXCLUDE_COMPANIES" | tr ',' '\n' | sed 's/^ *\(.*\) *$/  - "\1"/'
else
  echo "  []"
fi)

notes: |
  ${NOTES}

# Tracking — the agent updates these automatically
active_applications: []
last_search_run: ""
YAML

ok "Preferences saved to ${PREFS_FILE}"

# 2. Write env var
log "Updating .env..."
mkdir -p "$(dirname "$ENV_FILE")"
touch "$ENV_FILE"
env_set "JOB_SEARCH_PREFS_PATH" "${PREFS_FILE}"

# 3. Write agent definition to agents.json
log "Writing agent definition to agents.json..."
mkdir -p "$AGENTS_CONFIG_DIR"

AGENT_DEF=$(cat << JSON
{
  "name": "job-search",
  "description": "Helps with job searching: finding postings, drafting cover letters, tracking applications, and interview prep. Reads preferences from JOB_SEARCH_PREFS_PATH.",
  "trigger_phrases": ["job", "jobs", "career", "apply", "application", "resume", "interview", "recruiter", "hiring", "cover letter", "salary"],
  "model_tier": "sonnet",
  "system_prompt_snippet": "You are a strategic career coach and job search assistant. You help the user find and pursue job opportunities that match their preferences in ${PREFS_FILE}. You can draft cover letters, tailor resumes, prepare interview answers, research companies, and track application status. Always reference the user's actual preferences from their job-search.yaml before making recommendations. When the user lands a new application, offer to log it under active_applications in their prefs file.",
  "env_vars": ["JOB_SEARCH_PREFS_PATH"],
  "data_dir": "${CONFIG_DIR}"
}
JSON
)

if [[ ! -f "$AGENTS_JSON" ]]; then
  echo "[]" > "$AGENTS_JSON"
  ok "Created new agents.json"
fi

python3 - "$AGENTS_JSON" "$AGENT_DEF" << 'PYEOF'
import json, sys
path = sys.argv[1]
new_entry = json.loads(sys.argv[2])
with open(path) as f:
    agents = json.load(f)
agents = [a for a in agents if a.get("name") != "job-search"]
agents.append(new_entry)
with open(path, "w") as f:
    json.dump(agents, f, indent=2)
print("  [ok] job-search entry written to agents.json")
PYEOF

# 4. Print usage instructions
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Job Search Agent — Setup Complete"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  How to invoke via Telegram:"
echo ""
echo "    find me remote senior engineer jobs at SaaS companies"
echo "    write a cover letter for this job posting: [paste JD]"
echo "    I have an interview at Acme Corp — help me prep"
echo "    update my application to Stripe to 'phone screen scheduled'"
echo "    what roles match my profile?"
echo ""
echo "  Preferences file:"
echo "    ${PREFS_FILE}"
echo "    (Edit this to update your search criteria anytime)"
echo ""
echo "  Env var added to .env:"
echo "    JOB_SEARCH_PREFS_PATH=${PREFS_FILE}"
echo ""
echo "  Agent config updated at:"
echo "    ${AGENTS_JSON}"
echo ""
echo "  Tip: Paste a job description and say 'how well does this fit me?'"
echo "  to get a tailored match analysis before you apply."
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
