#!/usr/bin/env bash
# Module: secrets/env-only
# Simple .env-based secrets management. No external password manager required.

set -euo pipefail

ENV_FILE="${DEPLOY_BASE:-$HOME}/.env"
AGENT_NAME="${AGENT_NAME:-assistant}"

print_step() { echo ""; echo "  --> $1"; }
print_ok()   { echo "  [OK] $1"; }
print_warn() { echo "  [!]  $1"; }
print_info() { echo "       $1"; }

echo ""
echo "========================================"
echo "  Env-Only Secrets Setup"
echo "  Agent: $AGENT_NAME"
echo "========================================"
echo ""
echo "  All secrets for this assistant will be stored in:"
echo "  $ENV_FILE"
echo ""
echo "  No external password manager is required."
echo ""

# ── Step 1: Create .env if it does not exist ──────────────────────────────
print_step "Initializing .env file"
if [ ! -f "$ENV_FILE" ]; then
  touch "$ENV_FILE"
  print_ok "Created $ENV_FILE"
else
  print_ok "$ENV_FILE already exists"
fi

# ── Step 2: Set permissions ────────────────────────────────────────────────
chmod 600 "$ENV_FILE"
print_ok "Permissions set to 600 (owner read/write only)"

# ── Step 3: Verify permissions ────────────────────────────────────────────
PERMS=$(stat -c "%a" "$ENV_FILE" 2>/dev/null || stat -f "%A" "$ENV_FILE" 2>/dev/null || echo "unknown")
if [ "$PERMS" = "600" ]; then
  print_ok "Verified: $ENV_FILE is not readable by other users"
else
  print_warn "Could not verify permissions (reported: $PERMS). Check manually:"
  echo "    ls -la $ENV_FILE"
fi

# ── Step 4: Add header if file is new or empty ────────────────────────────
if [ ! -s "$ENV_FILE" ]; then
  cat >> "$ENV_FILE" << EOF
# .env — $AGENT_NAME assistant secrets
# Generated by personal-ai-playbook env-only module
#
# Add secrets in this format:
#   export SECRET_NAME="secret_value"
#
# Source this file in your shell or launch script:
#   source $ENV_FILE
#
# This file should NEVER be committed to git.
# Permissions are set to 600 (owner only).

EOF
  print_ok "Added header to $ENV_FILE"
fi

# ── Step 5: Check .gitignore ───────────────────────────────────────────────
print_step "Checking .gitignore protection"
GITIGNORE_DIR="${DEPLOY_BASE:-$HOME}"
GITIGNORE_FILE="$GITIGNORE_DIR/.gitignore"

ENV_BASENAME=$(basename "$ENV_FILE")

if [ -f "$GITIGNORE_FILE" ] && grep -q "$ENV_BASENAME" "$GITIGNORE_FILE" 2>/dev/null; then
  print_ok "$ENV_BASENAME is already listed in $GITIGNORE_FILE"
else
  echo ""
  echo "  If your deployment directory is a git repo, make sure your .env is ignored."
  echo "  Add to your .gitignore:"
  echo ""
  echo "    $ENV_BASENAME"
  echo "    *.env"
  echo "    .env.*"
  echo ""
  echo "  Or run:"
  echo "    echo '$ENV_BASENAME' >> $GITIGNORE_FILE"
fi

# ── Step 6: How to add secrets ────────────────────────────────────────────
print_step "How to add secrets"
echo ""
echo "  Open $ENV_FILE in your editor and add secrets in this format:"
echo ""
echo "    export MY_API_KEY=\"sk-abc123...\""
echo "    export DATABASE_PASSWORD=\"hunter2\""
echo "    export SERVICE_TOKEN=\"token_here\""
echo ""
echo "  Use UPPER_SNAKE_CASE for variable names."
echo "  Wrap values in double quotes."
echo ""
echo "  Your assistant sources this file at launch, so any variable you add"
echo "  will be available in the environment when your assistant runs."
echo ""

# ── Step 7: Security notes ────────────────────────────────────────────────
print_step "Security notes for env-only secrets"
echo ""
echo "  What this approach protects against:"
echo "  - Other users on the same machine reading your secrets"
echo "  - Accidental git commits of credentials"
echo "  - Secrets appearing in shell history (they are loaded from the file,"
echo "    not typed on the command line)"
echo ""
echo "  What this approach does NOT protect against:"
echo "  - Anyone with root or sudo access on this machine"
echo "  - Disk-level access (unencrypted drives)"
echo "  - Backups that include this file"
echo "  - Processes running as your user account"
echo ""
echo "  If you need stronger secret isolation, consider:"
echo "    - 1Password CLI  (modules/secrets/1password/install.sh)"
echo "    - Bitwarden CLI  (modules/secrets/bitwarden/install.sh)"
echo ""
echo "  For most personal assistant deployments on a machine you control,"
echo "  a chmod 600 .env is adequate."
echo ""

# ── Step 8: Confirm ────────────────────────────────────────────────────────
echo "========================================"
echo "  Env-only secrets module setup complete."
echo "  Secrets file: $ENV_FILE"
echo "  Permissions:  600"
echo "========================================"
echo ""
