#!/usr/bin/env bash
# Module: messaging/discord
# Sets up Discord integration for your Claude Code assistant.

set -euo pipefail

ENV_FILE="${DEPLOY_BASE:-$HOME}/.env"
AGENT_NAME="${AGENT_NAME:-assistant}"

print_step() { echo ""; echo "  --> $1"; }
print_ok()   { echo "  [OK] $1"; }
print_info() { echo "       $1"; }
print_warn() { echo "  [!]  $1"; }

echo ""
echo "========================================"
echo "  Discord Integration Setup"
echo "  Agent: $AGENT_NAME"
echo "========================================"

# ── Step 1: Check if token already exists ──────────────────────────────────
if grep -q "DISCORD_BOT_TOKEN" "$ENV_FILE" 2>/dev/null; then
  print_ok "DISCORD_BOT_TOKEN already present in $ENV_FILE"
  echo ""
  echo "  To reconfigure, remove the DISCORD_BOT_TOKEN line from $ENV_FILE"
  echo "  and re-run this installer."
  SKIP_TOKEN=true
else
  SKIP_TOKEN=false
fi

# ── Step 2: Developer Portal instructions ─────────────────────────────────
if [ "$SKIP_TOKEN" = false ]; then
  print_step "Create a Discord bot via the Developer Portal"
  echo ""
  echo "  1. Go to: https://discord.com/developers/applications"
  echo "  2. Click 'New Application' — give it a name (this becomes the bot's display name)"
  echo "  3. In the left sidebar, click 'Bot'"
  echo "  4. Click 'Add Bot' and confirm"
  echo "  5. Under the bot's username, click 'Reset Token' to generate a bot token"
  echo "     It will look like: MTIzNDU2Nzg5.XXXXXX.XXXXXXXXXXXXXXXXXXXXXXXX"
  echo "  6. Copy the token. You will need it next."
  echo ""
  echo "  Important bot settings (still in the Bot section):"
  echo "  - Enable 'Message Content Intent' under Privileged Gateway Intents"
  echo "  - Enable 'Server Members Intent' if you want member-aware features"
  echo ""

  while true; do
    read -rp "  Paste your Discord bot token: " BOT_TOKEN
    if [[ ${#BOT_TOKEN} -ge 50 ]]; then
      break
    else
      print_warn "That does not look like a valid Discord bot token (too short)."
      echo "  Try again, or Ctrl+C to exit."
    fi
  done

  echo "" >> "$ENV_FILE"
  echo "# Discord bot token (added by $AGENT_NAME discord module installer)" >> "$ENV_FILE"
  echo "export DISCORD_BOT_TOKEN=\"$BOT_TOKEN\"" >> "$ENV_FILE"
  print_ok "DISCORD_BOT_TOKEN saved to $ENV_FILE"
fi

# ── Step 3: Set permissions on .env ────────────────────────────────────────
chmod 600 "$ENV_FILE"
print_ok ".env permissions set to 600"

# ── Step 4: Add bot to your server ─────────────────────────────────────────
print_step "Add the bot to your Discord server"
echo ""
echo "  1. In the Discord Developer Portal, go to your application"
echo "  2. In the left sidebar, click 'OAuth2' > 'URL Generator'"
echo "  3. Under 'Scopes', check: bot, applications.commands"
echo "  4. Under 'Bot Permissions', check: Send Messages, Read Message History,"
echo "     View Channels, and any others you need"
echo "  5. Copy the generated URL and open it in your browser"
echo "  6. Select the server you want to add the bot to and authorize"
echo ""
echo "  Tip: For a private assistant, create a dedicated server or a private channel"
echo "  and only invite the bot there."
echo ""

# ── Step 5: How to start Claude Code with Discord ──────────────────────────
print_step "Starting your assistant with Discord"
echo ""
echo "  Load your .env and start Claude Code with the Discord plugin:"
echo ""
echo "    source $ENV_FILE"
echo "    claude --channels plugin:discord@claude-plugins-official \\"
echo "           --system-prompt \"\$(cat \$SOUL_FILE)\" \\"
echo "           --dangerously-skip-permissions"
echo ""
echo "  If you are using the launch script generated by setup.sh:"
echo ""
echo "    ${DEPLOY_BASE:-$HOME}/.${AGENT_NAME}/launch.sh"
echo ""

# ── Step 6: Server setup recommendations ──────────────────────────────────
print_step "Recommended server setup"
echo ""
echo "  For a private assistant on Discord:"
echo ""
echo "  1. Create a new server (or use an existing private one)"
echo "  2. Create a dedicated channel for your assistant (e.g., #assistant)"
echo "  3. Set the channel permissions so only you (and the bot) can see it"
echo "  4. In that channel, @mention the bot or just send messages directly"
echo ""
echo "  The bot will only respond in channels it has access to."
echo ""

# ── Step 7: Verify environment ─────────────────────────────────────────────
print_step "Verifying setup"
source "$ENV_FILE"
if [ -n "${DISCORD_BOT_TOKEN:-}" ]; then
  print_ok "DISCORD_BOT_TOKEN is set in the environment"
else
  print_warn "DISCORD_BOT_TOKEN is not loading from $ENV_FILE — check the file manually"
fi

echo ""
echo "========================================"
echo "  Discord module setup complete."
echo "========================================"
echo ""
