#!/usr/bin/env bash
# rotate-logs.sh — Rotate session logs and assistant logs using logrotate.
#
# Runs logrotate with the agent's logrotate config.
# If no config exists, creates a sensible default and runs it.
#
# Environment:
#   AGENT_RUNTIME_DIR  — base runtime directory (default: ~/.assistant)
#   AGENT_NAME         — name of the agent (default: assistant)

set -euo pipefail

# ── Environment ───────────────────────────────────────────────────────────
AGENT_RUNTIME_DIR="${AGENT_RUNTIME_DIR:-$HOME/.assistant}"
AGENT_NAME="${AGENT_NAME:-assistant}"
CONFIG_DIR="$AGENT_RUNTIME_DIR/config"
LOGROTATE_CONF="$CONFIG_DIR/logrotate.conf"
STATE_DIR="$AGENT_RUNTIME_DIR/state"
LOG_DIR="$STATE_DIR/session-logs"
LOGROTATE_STATE="$STATE_DIR/logrotate.status"

# ── Logging ───────────────────────────────────────────────────────────────
log() {
  echo "[rotate-logs $(date -u +%H:%M:%SZ)] $*"
}

log "Starting log rotation for $AGENT_NAME"

# ── Check for logrotate ───────────────────────────────────────────────────
if ! command -v logrotate &>/dev/null; then
  log "logrotate not found"
  echo "" >&2
  echo "  logrotate is required for log rotation." >&2
  echo "" >&2
  echo "  Install it:" >&2
  if [[ "$(uname -s)" == "Darwin" ]]; then
    echo "    brew install logrotate" >&2
  else
    echo "    sudo apt install logrotate   # Debian/Ubuntu" >&2
    echo "    sudo yum install logrotate   # RHEL/CentOS" >&2
    echo "    sudo dnf install logrotate   # Fedora" >&2
  fi
  echo "" >&2
  exit 1
fi

# ── Create config directory ───────────────────────────────────────────────
mkdir -p "$CONFIG_DIR"
mkdir -p "$STATE_DIR"

# ── Create default logrotate config if missing ────────────────────────────
if [ ! -f "$LOGROTATE_CONF" ]; then
  log "No logrotate config found — creating default at $LOGROTATE_CONF"

  cat > "$LOGROTATE_CONF" << EOF
# Logrotate configuration for $AGENT_NAME assistant
# Generated by rotate-logs.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
#
# Rotate session JSONL logs: keep 90 days, compress old files

$LOG_DIR/*.jsonl {
    daily
    rotate 90
    compress
    delaycompress
    missingok
    notifempty
    dateext
    dateformat -%Y-%m-%d
    extension .jsonl
    su $(id -un) $(id -gn)
}

# Rotate the LCM cron log if present
$STATE_DIR/lcm-cron.log {
    weekly
    rotate 4
    compress
    delaycompress
    missingok
    notifempty
    su $(id -un) $(id -gn)
}
EOF

  log "Default logrotate config created"
fi

# ── Run logrotate ─────────────────────────────────────────────────────────
log "Running logrotate..."
log "Config: $LOGROTATE_CONF"
log "State:  $LOGROTATE_STATE"
echo ""

# logrotate requires its state file to exist or be writable
LOGROTATE_OUTPUT=$(logrotate \
  --state "$LOGROTATE_STATE" \
  --verbose \
  "$LOGROTATE_CONF" 2>&1) || LOGROTATE_EXIT=$?

if [ "${LOGROTATE_EXIT:-0}" -ne 0 ]; then
  log "logrotate exited with code ${LOGROTATE_EXIT:-0}"
  echo "$LOGROTATE_OUTPUT" | sed 's/^/  /'
  echo ""
  log "Common issues:"
  echo "  - Log directory does not exist yet: $LOG_DIR"
  echo "  - 'su' directive: try removing it from $LOGROTATE_CONF if running as your own user"
  echo "  - Config path ownership: logrotate may reject configs not owned by root"
  echo "    Workaround: logrotate --state $LOGROTATE_STATE $LOGROTATE_CONF"
  exit "${LOGROTATE_EXIT:-1}"
fi

echo "$LOGROTATE_OUTPUT" | sed 's/^/  /'
echo ""
log "Log rotation complete"

# ── Show current log stats ────────────────────────────────────────────────
if [ -d "$LOG_DIR" ]; then
  JSONL_COUNT=$(find "$LOG_DIR" -name "*.jsonl" 2>/dev/null | wc -l | tr -d ' ')
  JSONL_GZ_COUNT=$(find "$LOG_DIR" -name "*.jsonl.gz" 2>/dev/null | wc -l | tr -d ' ')
  TOTAL_SIZE=$(du -sh "$LOG_DIR" 2>/dev/null | cut -f1 || echo "unknown")

  echo ""
  log "Log directory summary: $LOG_DIR"
  echo "  Active logs:      $JSONL_COUNT .jsonl files"
  echo "  Compressed logs:  $JSONL_GZ_COUNT .jsonl.gz files"
  echo "  Total size:       $TOTAL_SIZE"
fi
