#!/usr/bin/env bash
# Module: messaging/telegram
# Sets up Telegram integration for your Claude Code assistant.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${DEPLOY_BASE:-$HOME}/.env"
AGENT_NAME="${AGENT_NAME:-assistant}"

print_step() { echo ""; echo "  --> $1"; }
print_ok()   { echo "  [OK] $1"; }
print_info() { echo "       $1"; }
print_warn() { echo "  [!]  $1"; }

echo ""
echo "========================================"
echo "  Telegram Integration Setup"
echo "  Agent: $AGENT_NAME"
echo "========================================"

# ── Step 1: Check if token already exists ──────────────────────────────────
if grep -q "TELEGRAM_BOT_TOKEN" "$ENV_FILE" 2>/dev/null; then
  print_ok "TELEGRAM_BOT_TOKEN already present in $ENV_FILE"
  echo ""
  echo "  To reconfigure, remove the TELEGRAM_BOT_TOKEN line from $ENV_FILE"
  echo "  and re-run this installer."
  SKIP_TOKEN=true
else
  SKIP_TOKEN=false
fi

# ── Step 2: BotFather instructions ─────────────────────────────────────────
if [ "$SKIP_TOKEN" = false ]; then
  print_step "Create a Telegram bot via BotFather"
  echo ""
  echo "  1. Open Telegram and search for @BotFather"
  echo "  2. Send: /newbot"
  echo "  3. Follow the prompts — choose a name and a username (must end in 'bot')"
  echo "     Example username: myassistant_bot"
  echo "  4. BotFather will reply with a token that looks like:"
  echo "     123456789:ABCdefGHIjklMNOpqrSTUVwxyz"
  echo ""
  echo "  Copy that token. You will enter it next."
  echo ""

  while true; do
    read -rp "  Paste your Telegram bot token: " BOT_TOKEN
    if [[ "$BOT_TOKEN" =~ ^[0-9]+:[A-Za-z0-9_-]{35,}$ ]]; then
      break
    else
      print_warn "That does not look like a valid bot token. Format: 123456789:ABCdefGHI..."
      echo "  Try again, or Ctrl+C to exit."
    fi
  done

  # Append to .env
  echo "" >> "$ENV_FILE"
  echo "# Telegram bot token (added by $AGENT_NAME telegram module installer)" >> "$ENV_FILE"
  echo "export TELEGRAM_BOT_TOKEN=\"$BOT_TOKEN\"" >> "$ENV_FILE"
  print_ok "TELEGRAM_BOT_TOKEN saved to $ENV_FILE"
fi

# ── Step 3: Set permissions on .env ────────────────────────────────────────
chmod 600 "$ENV_FILE"
print_ok ".env permissions set to 600"

# ── Step 4: How to start Claude Code with Telegram ─────────────────────────
print_step "Starting your assistant with Telegram"
echo ""
echo "  Load your .env file and start Claude Code with the Telegram plugin:"
echo ""
echo "    source $ENV_FILE"
echo "    claude --channels plugin:telegram@claude-plugins-official \\"
echo "           --system-prompt \"\$(cat \$SOUL_FILE)\" \\"
echo "           --dangerously-skip-permissions"
echo ""
echo "  Where SOUL_FILE is the path to your SOUL.md persona file."
echo ""
echo "  If you are using the launch script generated by setup.sh, it will"
echo "  handle this automatically. Just run:"
echo ""
echo "    ${DEPLOY_BASE:-$HOME}/.${AGENT_NAME}/launch.sh"
echo ""

# ── Step 5: Pairing instructions ───────────────────────────────────────────
print_step "Pair your Telegram account with the bot"
echo ""
echo "  After starting your assistant:"
echo ""
echo "  1. Open Telegram and find your bot (search by the username you chose)"
echo "  2. Send the bot any message — it will respond with a pairing code"
echo "     or a prompt to approve in your terminal"
echo "  3. In your terminal, you will see a pairing request. Type 'yes' to approve."
echo "  4. You are now connected. Messages you send to the bot will reach your assistant."
echo ""
echo "  Only your Telegram account will be approved. Other users messaging your bot"
echo "  will not be connected to your assistant session."
echo ""

# ── Step 6: Verify environment ─────────────────────────────────────────────
print_step "Verifying setup"
source "$ENV_FILE"
if [ -n "${TELEGRAM_BOT_TOKEN:-}" ]; then
  print_ok "TELEGRAM_BOT_TOKEN is set in the environment"
else
  print_warn "TELEGRAM_BOT_TOKEN is not loading from $ENV_FILE — check the file manually"
fi

echo ""
echo "========================================"
echo "  Telegram module setup complete."
echo "========================================"
echo ""
